name: Kubescape scanning for misconfigurations
on: [push, pull_request]
jobs:
  kubescape-scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - uses: actions/checkout@v3
    - uses: MMMMMMorty/github-action@main
      continue-on-error: true
      with:
        format: sarif
        outputFile: results.sarif
        # Kubescape cloud account ID
        account: ${{secrets.KUBESCAPE_ACCOUNT}}
        # # Optional - Scan a specific path. Default will scan all
        # files: "examples/*.yaml"
    - name: PR Suggester according to SARIF file
      uses: HollowMan6/sarif4reviewdog@v1.0.0
      with:
        file: 'results.sarif'
        level: warning
    - name: Print result
      run: cat results.sarif
    - name: Upload Kubescape scan results to Github Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
